KINDLE_EMAIL        = 'youremail@example.com'
KINDLE_PASSWORD     = 'YourPassword'
LINE_CHANNEL_SECRET = 'YourChannelSecret'
LINE_CHANNEL_TOKEN  = 'YourChannelToken'
LINE_USER_ID        = 'YourUserID'
